FROM ubuntu:18.04

RUN apt-get update && apt-get install -y tzdata && apt-get install -y \
    ca-certificates \
    curl \
    --no-install-recommends \
    git \
    java-common \
    libisl15 \
    openjdk-11-jdk \
    sudo \
    unzip \
    wget \
    zip \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /
